version: '3.3'
services:
  api:
    build: .
    ports:
      - '8081:8080'
    networks:
      - golang_mongo
  mongo:
    image: 'mongo:7.0.0-rc2'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: golang
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./data/dev/mongo:/data/db
    restart: always
    networks:
      - golang_mongo
networks:
  golang_mongo:
    driver: bridge
