openapi: 3.0.0
info:
  title: API
  version: 1.0.0

paths:
  /api/version:
    get:
      summary: Get latest version
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                    example: "1.0.0"
              examples:
                version-example:
                  value:
                    value: "1.0.0"
